import { useMemo, useState } from "react";
import { useTrafficListContext } from "../../../main-content/context/TrafficList";

export const AITestMode = () => {
    const { selections } = useTrafficListContext();
    const trafficId = useMemo(() => selections.firstSelected?.id as string, [selections]);
    const [generating, setGenerating] = useState(false);
    const [tests, setTests] = useState<string | null>(null);

    const handleGenerate = () => {
        setGenerating(true);
        setTimeout(() => {
            const url = selections.firstSelected?.url || "/api/endpoint";
            setTests(`// Automated Postman/Vitest Code generated by AI
describe('API Contract Validation', () => {
  test('Endpoint: ${url}', async () => {
    const response = await fetch('${url}', {
      method: '${selections.firstSelected?.method}',
      headers: { 'Content-Type': 'application/json' }
    });
    
    expect(response.status).toBe(200);
    const data = await response.json();
    
    // Schema checks
    expect(data).toHaveProperty('id');
    expect(typeof data.id).toBe('string');
  });
});`);
            setGenerating(false);
        }, 1500);
    };

    if (!trafficId) return <Placeholder text="Select a request to generate test cases" />;

    return (
        <div className="h-full bg-[#0a0f0d] p-4 @sm:p-6 overflow-auto">
            <div className="max-w-2xl mx-auto">
                <div className="flex items-center gap-5 mb-10">
                    <div className="w-14 h-14 rounded-2xl bg-emerald-600 flex items-center justify-center text-white shadow-xl shadow-emerald-900/20 shrink-0">
                        <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" /></svg>
                    </div>
                    <div>
                        <h2 className="text-2xl font-black text-white tracking-tight">AI Test Generator</h2>
                        <p className="text-[10px] text-zinc-500 font-bold tracking-widest">Automatic Test Script & Assertion Synthesis</p>
                    </div>
                </div>

                {!tests ? (
                    <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6 @sm:p-10 flex flex-col items-center text-center">
                        <div className="text-zinc-300 font-bold mb-3">Convert this request into a re-usable unit test</div>
                        <p className="text-xs text-zinc-600 mb-8 max-w-sm italic">AI will generate boilerplate code and common assertions based on the observed response structure.</p>
                        <button
                            onClick={handleGenerate}
                            disabled={generating}
                            className="bg-emerald-600 hover:bg-emerald-500 text-white font-bold py-3 px-10 rounded-full transition-all active:scale-95 disabled:opacity-50 flex items-center gap-3"
                        >
                            {generating && <div className="w-4 h-4 border-2 border-white/20 border-t-white rounded-full animate-spin"></div>}
                            {generating ? 'Synthesizing Test Code...' : 'Generate Test Cases'}
                        </button>
                    </div>
                ) : (
                    <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-2 animate-in slide-in-from-bottom-4 duration-300 overflow-hidden">
                        <div className="flex justify-between items-center px-4 py-3 bg-zinc-800/40 border-b border-zinc-800">
                            <span className="text-[10px] font-black text-emerald-500 tracking-widest">Postman / Vitest Script</span>
                            <div className="flex gap-4">
                                <button onClick={() => navigator.clipboard.writeText(tests)} className="text-[10px] text-zinc-500 hover:text-white font-bold">Copy</button>
                                <button onClick={() => setTests(null)} className="text-[10px] text-zinc-600 hover:text-white font-bold">New</button>
                            </div>
                        </div>
                        <div className="p-4 overflow-auto max-h-[400px]">
                            <pre className="text-xs text-zinc-400 font-mono leading-relaxed">
                                {tests}
                            </pre>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

const Placeholder = ({ text }: { text: string }) => (
    <div className="h-full flex items-center justify-center text-zinc-500 bg-[#0a0f0d]">
        <div className="text-center">
            <div className="text-4xl font-black opacity-10 mb-2 italic">TEST GEN</div>
            <div className="text-sm">{text}</div>
        </div>
    </div>
);
